# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('stock_id', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
