# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMetrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('portfolio_value', models.FloatField()),
                ('buying_power', models.FloatField()),
                ('withdrawable_cash', models.FloatField()),
                ('cash_balance', models.FloatField()),
                ('invested_fund', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('stock_id', models.IntegerField()),
            ],
        ),
    ]
