# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMetrics', '0002_portfolio_stockmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='title',
            new_name='Stock_Name',
        ),
        migrations.RemoveField(
            model_name='stockmetrics',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stockmetrics',
            name='Metric_Title',
            field=models.CharField(choices=[('RSI', 'Relative Strength Index (RSI)'), ('OBV', 'On Balance Volume (OBV)'), ('AI', 'Aroon Indicator'), ('SMA', 'Simple Moving Average'), ('SO', 'Stochastic Oscillator')], default=('RSI', 'Relative Strength Index (RSI)'), max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
