# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMetrics', '0003_auto_20171101_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='Stock_Name',
            new_name='StockName',
        ),
    ]
